language: cpp

dist: bionic

compiler: gcc

before_install:
  - sudo sh install_ubuntu_bionic.sh
  - sudo sh install_libs.sh

script:
  - source /opt/ros/dashing/setup.bash 
  - cd src/nexus_interface/ && colcon build 

